// 20종 픽셀 스프라이트 데이터 (16×16 그리드)
// 팔레트 키: B=몸통, A=포인트색, K=외곽선, N=코(분홍), E=눈(무드별 렌더링)
// '.' = 투명 | 각 행 정확히 16자

export interface SpriteFrameData {
  map: readonly string[];
  eyeColor: 'outline' | 'accent';
}

export interface AnimalPixelData {
  baby:      SpriteFrameData;
  childhood: SpriteFrameData;
  growth:    SpriteFrameData;
  maturity:  SpriteFrameData;
}

// ─── 강아지 (dog) - 축 늘어진 플랩 귀 ───
const DOG: AnimalPixelData = {
  baby: {
    eyeColor: 'outline',
    map: [
      '................',
      '................',
      '..KAAK....KAAK..',
      '..KABB....BBAK..',
      '...KABBBBBBBBAK.',
      '...KAB.EE.EE.AK.',
      '...KABBBBBBBBAK.',
      '...KAB..NN..BAK.',
      '...KABBBBBBBBAK.',
      '....KABBBBBBBAK.',
      '.....KBBBBBBBK..',
      '......KBBBBBK...',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  childhood: {
    eyeColor: 'outline',
    map: [
      '................',
      '.KAAK......KAAK.',
      '.KABB......BBAK.',
      '.KABBBBBBBBBBBAK',
      '.KAB.EE.EE..BAK.',
      '.KABBBBBBBBBBBAK',
      '.KAB..NN...BBAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBBAK.',
      '..KBBBBBBBBBBBK.',
      '..KBB.......BBK.',
      '..KBB.......BBK.',
      '...KK.......KK..',
      '................',
      '................',
      '................',
    ],
  },
  growth: {
    eyeColor: 'outline',
    map: [
      'KAAK........KAAK',
      'KABB........BBAK',
      'KABBBBBBBBBBBBAK',
      'KAB.EE..EE..BBAK',
      'KABBBBBBBBBBBBAK',
      'KAB..NN....BBAK.',
      'KABBBBBBBBBBBBAK',
      '.KABBBBBBBBBBBAK',
      '.KBBBBBBBBBBBBK.',
      '.KBB..KBBK..BBK.',
      '.KBB..KBBK..BBK.',
      '..KK..KBBK..KK..',
      '......KBBK......',
      '......KBBK......',
      '.......KK.......',
      '................',
    ],
  },
  maturity: {
    eyeColor: 'outline',
    map: [
      'KAAK........KAAK',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KAB.EE....EE.BAK',
      'KABBBBBBBBBBBBAK',
      'KAB..NNN...BBAK.',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KBBBBBBBBBBBBBBK',
      'KBB..KBBBBK..BBK',
      'KBB..KBBBBK..BBK',
      '.KK..KBBBBK..KK.',
      '.....KBBBBK.....',
      '.....KBBBBK.....',
      '......KBBK......',
      '................',
    ],
  },
};

// ─── 고양이 (cat) - 뾰족한 삼각 귀 ───
const CAT: AnimalPixelData = {
  baby: {
    eyeColor: 'outline',
    map: [
      '................',
      '................',
      '....K......K....',
      '...KAK....KAK...',
      '..KABBBBBBBBBAK.',
      '..KAB.EE.EE.BAK.',
      '..KABBBBBBBBBAK.',
      '..KAB..NN..BAK..',
      '..KABBBBBBBBBAK.',
      '...KABBBBBBBAK..',
      '....KBBBBBBBK...',
      '.....KBBBBBK....',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  childhood: {
    eyeColor: 'outline',
    map: [
      '................',
      '...K.......K....',
      '..KAK.....KAK...',
      '.KABBBBBBBBBBBAK',
      '.KAB.EE.EE..BAK.',
      '.KABBBBBBBBBBBAK',
      '.KAB..NN...BBAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBBAK.',
      '..KBBBBBBBBBBBK.',
      '..KBB.......BBK.',
      '..KBB.......BBK.',
      '...KK.......KK..',
      '................',
      '................',
      '................',
    ],
  },
  growth: {
    eyeColor: 'outline',
    map: [
      '..K.........K...',
      '.KAK.......KAK..',
      'KABBBBBBBBBBBBAK',
      'KAB.EE..EE..BBAK',
      'KABBBBBBBBBBBBAK',
      'KAB..NN....BBAK.',
      'KABBBBBBBBBBBBAK',
      '.KABBBBBBBBBBBAK',
      '.KBBBBBBBBBBBBK.',
      '.KBB..KBBK..BBK.',
      '.KBB..KBBK..BBK.',
      '..KK..KBBK..KK..',
      '......KBBK......',
      '......KBBK......',
      '.......KK.......',
      '................',
    ],
  },
  maturity: {
    eyeColor: 'outline',
    map: [
      '.K...........K..',
      'KAK.........KAK.',
      'KABBBBBBBBBBBBAK',
      'KAB.EE....EE.BAK',
      'KABBBBBBBBBBBBAK',
      'KAB..NNN...BBAK.',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KBBBBBBBBBBBBBBK',
      'KBB..KBBBBK..BBK',
      'KBB..KBBBBK..BBK',
      '.KK..KBBBBK..KK.',
      '.....KBBBBK.....',
      '.....KBBBBK.....',
      '......KBBK......',
      '................',
    ],
  },
};

// ─── 토끼 (rabbit) - 매우 긴 수직 귀 ───
const RABBIT: AnimalPixelData = {
  baby: {
    eyeColor: 'outline',
    map: [
      '....KAK.KAK.....',
      '....KAK.KAK.....',
      '....KAK.KAK.....',
      '...KABK.KBAK....',
      '..KABBBBBBBBBAK.',
      '..KAB.EE.EE.BAK.',
      '..KABBBBBBBBBAK.',
      '..KAB..NN..BAK..',
      '..KABBBBBBBBBAK.',
      '...KABBBBBBBAK..',
      '....KBBBBBBBK...',
      '.....KBBBBBK....',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  childhood: {
    eyeColor: 'outline',
    map: [
      '...KAK...KAK....',
      '...KAK...KAK....',
      '...KAK...KAK....',
      '..KABK...KBAK...',
      '.KABBBBBBBBBBBAK',
      '.KAB.EE.EE..BAK.',
      '.KABBBBBBBBBBBAK',
      '.KAB..NN...BBAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBBAK.',
      '..KBBBBBBBBBBBK.',
      '..KBB.......BBK.',
      '...KK.......KK..',
      '................',
      '................',
      '................',
    ],
  },
  growth: {
    eyeColor: 'outline',
    map: [
      '..KAK.....KAK...',
      '..KAK.....KAK...',
      '..KAK.....KAK...',
      '.KABK.....KBAK..',
      'KABBBBBBBBBBBBAK',
      'KAB.EE..EE..BBAK',
      'KABBBBBBBBBBBBAK',
      'KAB..NN....BBAK.',
      'KABBBBBBBBBBBBAK',
      '.KABBBBBBBBBBBAK',
      '.KBBBBBBBBBBBBK.',
      '.KBB..KBBK..BBK.',
      '..KK..KBBK..KK..',
      '......KBBK......',
      '.......KK.......',
      '................',
    ],
  },
  maturity: {
    eyeColor: 'outline',
    map: [
      '.KAK.......KAK..',
      '.KAK.......KAK..',
      '.KAK.......KAK..',
      'KABK.......KBAK.',
      'KABBBBBBBBBBBBAK',
      'KAB.EE....EE.BAK',
      'KABBBBBBBBBBBBAK',
      'KAB..NNN...BBAK.',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KBBBBBBBBBBBBBBK',
      'KBB..KBBBBK..BBK',
      '.KK..KBBBBK..KK.',
      '.....KBBBBK.....',
      '......KBBK......',
      '................',
    ],
  },
};

// ─── 여우 (fox) - 뾰족한 각진 귀, 주황 몸, A색 주둥이 ───
const FOX: AnimalPixelData = {
  baby: {
    eyeColor: 'outline',
    map: [
      '................',
      '................',
      '..K.......K.....',
      '..AK......KA....',
      '..AABBBBBBBBAAK.',
      '..AAB.EE.EE.BAK.',
      '..AABBBBBBBBAAK.',
      '..AAB..NN..BAK..',
      '..AABBBBBBBBAAK.',
      '...AABBBBBBBAAK.',
      '....KBBBBBBBK...',
      '.....KBBBBBK....',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  childhood: {
    eyeColor: 'outline',
    map: [
      '................',
      '.K..........K...',
      '.AK.........KA..',
      '.AABBBBBBBBBBAAK',
      '.AAB.EE.EE..BAK.',
      '.AABBBBBBBBBBAAK',
      '.AAB..NN...BBAK.',
      '.AABBBBBBBBBBAAK',
      '..AABBBBBBBBBAAK',
      '..KBBBBBBBBBBBK.',
      '..KBB.......BBK.',
      '..KBB.......BBK.',
      '...KK.......KK..',
      '................',
      '................',
      '................',
    ],
  },
  growth: {
    eyeColor: 'outline',
    map: [
      'K...........K...',
      'AK..........KA..',
      'AABBBBBBBBBBBBAK',
      'AAB.EE..EE..BBAK',
      'AABBBBBBBBBBBBAK',
      'AAB..NN....BBAK.',
      'AABBBBBBBBBBBBAK',
      '.AABBBBBBBBBBAAK',
      '.KBBBBBBBBBBBBK.',
      '.KBB..KBBK..BBK.',
      '.KBB..KBBK..BBK.',
      '..KK..KBBK..KK..',
      '......KBBK......',
      '......KBBK......',
      '.......KK.......',
      '................',
    ],
  },
  maturity: {
    eyeColor: 'outline',
    map: [
      'K...........K...',
      'AK..........KA..',
      'AABBBBBBBBBBBBAK',
      'AAB.EE....EE.BAK',
      'AABBBBBBBBBBBBAK',
      'AAB..NNN...BBAK.',
      'AABBBBBBBBBBBBAK',
      'AABBBBBBBBBBBBAK',
      'KBBBBBBBBBBBBBBK',
      'KBB..KBBBBK..BBK',
      'KBB..KBBBBK..BBK',
      '.KK..KBBBBK..KK.',
      '.....KBBBBK.....',
      '.....KBBBBK.....',
      '......KBBK......',
      '................',
    ],
  },
};

// ─── 판다 (panda) - 흰 몸(B), 검은 귀/눈패치(A) ───
const PANDA: AnimalPixelData = {
  baby: {
    eyeColor: 'accent',
    map: [
      '................',
      '................',
      '...KAAK..KAAK...',
      '..KABBBBBBBBBAK.',
      '..KABBAEBAEBBAK.',
      '..KABBAAAAABBAK.',
      '..KABBAEBAEBBAK.',
      '..KABB..NN.BBAK.',
      '..KABBBBBBBBBAK.',
      '...KABBBBBBBAK..',
      '....KBBBBBBBK...',
      '.....KBBBBBK....',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  childhood: {
    eyeColor: 'accent',
    map: [
      '................',
      '..KAAK....KAAK..',
      '.KABBBBBBBBBBBAK',
      '.KAB.AEA.AEA.AK.',
      '.KABBAAAAAAAABAK',
      '.KAB.AEA.AEA.AK.',
      '.KAB...NN...BAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBBAK.',
      '..KBBBBBBBBBBBK.',
      '..KBB.......BBK.',
      '..KBB.......BBK.',
      '...KK.......KK..',
      '................',
      '................',
      '................',
    ],
  },
  growth: {
    eyeColor: 'accent',
    map: [
      '.KAAK.......KAAK',
      'KABBBBBBBBBBBBAK',
      'KAB.AEA..AEA.BAK',
      'KABBAAAAAAAABBAK',
      'KAB.AEA..AEA.BAK',
      'KAB...NN....BAK.',
      'KABBBBBBBBBBBBAK',
      '.KABBBBBBBBBBBAK',
      '.KBBBBBBBBBBBBK.',
      '.KBB..KBBK..BBK.',
      '.KBB..KBBK..BBK.',
      '..KK..KBBK..KK..',
      '......KBBK......',
      '......KBBK......',
      '.......KK.......',
      '................',
    ],
  },
  maturity: {
    eyeColor: 'accent',
    map: [
      'KAAK........KAAK',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KAB.AEA..AEA.BAK',
      'KABBAAAAAAAABBAK',
      'KAB.AEA..AEA.BAK',
      'KAB...NNN...BBAK',
      'KABBBBBBBBBBBBAK',
      'KBBBBBBBBBBBBBBK',
      'KBB..KBBBBK..BBK',
      'KBB..KBBBBK..BBK',
      '.KK..KBBBBK..KK.',
      '.....KBBBBK.....',
      '.....KBBBBK.....',
      '......KBBK......',
      '................',
    ],
  },
};

export const PIX = { dog: DOG, cat: CAT, rabbit: RABBIT, fox: FOX, panda: PANDA };
