// 20종 픽셀 스프라이트 데이터 (16×16 그리드)
// 팔레트 키: B=몸통, A=포인트색, K=외곽선/어둠, N=코, E=눈(무드별 렌더링)
// '.' = 투명

export interface SpriteFrameData {
  map: readonly string[];   // 16행 × 16열
  eyeColor: 'outline' | 'accent'; // 눈에 사용할 색
}

export interface AnimalPixelData {
  baby:      SpriteFrameData;
  childhood: SpriteFrameData;
  growth:    SpriteFrameData;
  maturity:  SpriteFrameData;
}

// ─── 강아지 (dog) - 축 늘어진 플랩 귀, 따뜻한 갈색 ───
const DOG: AnimalPixelData = {
  baby: {
    eyeColor: 'outline',
    map: [
      '................',
      '....KAAK.KAAK...',
      '...KABBBBBBBBAK.',
      '..KABBBBBBBBBAK.',
      '..KABB.EE.EE.AK.',
      '..KABBBBBBBBBAK.',
      '..KABB.NNNN.BAK.',
      '..KABBBBBBBBBAK.',
      '...KABBBBBBBBAK.',
      '....KBBBBBBBBK..',
      '....KBBBBBBBBK..',
      '.....KBBBBBBK...',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  childhood: {
    eyeColor: 'outline',
    map: [
      '...KAAK..KAAK...',
      '..KABBBBBBBBBAK.',
      '.KABBBBBBBBBBBAK',
      '.KABB.EE..EE.BAK',
      '.KABBBBBBBBBBBAK',
      '.KABB.NNNN.BBAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBAK..',
      '..KBBBBBBBBBBK..',
      '..KBBBBBBBBBBK..',
      '..KBB......BBK..',
      '..KBB......BBK..',
      '...KK......KK...',
      '................',
      '................',
      '................',
    ],
  },
  growth: {
    eyeColor: 'outline',
    map: [
      '..KAAK....KAAK..',
      '.KABBBBBBBBBBBAK',
      'KABBBBBBBBBBBAK.',
      'KAB..EE..EE..BAK',
      'KABBBBBBBBBBBAK.',
      'KAB..NNNN..BAK..',
      'KABBBBBBBBBBBAK.',
      '.KABBBBBBBBBBBAK',
      '.KBBBBBBBBBBBBK.',
      '.KBBBBBBBBBBBBK.',
      '.KBB........BBK.',
      '.KBB.K....K.BBK.',
      '.KBB.K....K.BBK.',
      '..KK.K....K.KK..',
      '................',
      '................',
    ],
  },
  maturity: {
    eyeColor: 'outline',
    map: [
      '.KAAK......KAAK.',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KAB.EE....EE.BAK',
      'KABBBBBBBBBBBBAK',
      'KAB.NNNNNN.BBAK.',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KBBBBBBBBBBBBBBK',
      'KBBBBBBBBBBBBBBK',
      'KBB..KBBBBK..BBK',
      'KBB..KBBBBK..BBK',
      '.KK..KBBBBK..KK.',
      '................',
      '................',
      '................',
    ],
  },
};

// ─── 고양이 (cat) - 뾰족한 삼각 귀, 날렵한 몸 ───
const CAT: AnimalPixelData = {
  baby: {
    eyeColor: 'outline',
    map: [
      '....KAK..KAK....',
      '...KAAK..KAAK...',
      '..KABBBBBBBBBAK.',
      '.KABBBBBBBBBBBAK',
      '.KABB.EE.EE.BAK.',
      '.KABBBBBBBBBBBAK',
      '.KABB.NNNN.BBAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBAK..',
      '...KABBBBBBBAK..',
      '....KBBBBBBBBK..',
      '....KBBBBBBBBK..',
      '.....KBBBBBBK...',
      '................',
      '................',
      '................',
    ],
  },
  childhood: {
    eyeColor: 'outline',
    map: [
      '..KAK......KAK..',
      '.KAAK......KAAK.',
      '.KABBBBBBBBBBBAK',
      'KABBBBBBBBBBBAK.',
      'KAB.EE....EE.BAK',
      'KABBBBBBBBBBBAK.',
      'KAB..NNNN..BAK..',
      'KABBBBBBBBBBBAK.',
      '.KABBBBBBBBBBAK.',
      '.KBBBBBBBBBBBBK.',
      '.KBBBBBBBBBBBBK.',
      '.KBB......BBK...',
      '.KBB......BBK...',
      '..KK......KK....',
      '................',
      '................',
    ],
  },
  growth: {
    eyeColor: 'outline',
    map: [
      '...KAK....KAK...',
      '..KAAK....KAAK..',
      '.KABBBBBBBBBBBAK',
      'KABBBBBBBBBBBAK.',
      'KAB..EE..EE..BAK',
      'KABBBBBBBBBBBAK.',
      'KAB..NNNN..BAK..',
      'KABBBBBBBBBBBAK.',
      '.KABBBBBBBBBBBAK',
      '.KBBBBBBBBBBBBK.',
      'KBBBBBBBBBBBBBBK',
      'KBBBBBBBBBBBBBBK',
      '.KBB........BBK.',
      '.KBB.K....K.BBK.',
      '..KK.K....K.KK..',
      '................',
    ],
  },
  maturity: {
    eyeColor: 'outline',
    map: [
      '..KAK......KAK..',
      '.KAAK......KAAK.',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KAB.EE....EE.BAK',
      'KABBBBBBBBBBBBAK',
      'KAB.NNNNNN.BBAK.',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KBBBBBBBBBBBBBBK',
      'KBBBBBBBBBBBBBBK',
      'KBB..KBBBBK..BBK',
      'KBB..KBBBBK..BBK',
      '.KK..KBBBBK..KK.',
      '................',
      '................',
    ],
  },
};

// ─── 토끼 (rabbit) - 매우 긴 귀, 동그란 몸 ───
const RABBIT: AnimalPixelData = {
  baby: {
    eyeColor: 'outline',
    map: [
      '.....KAK.KAK....',
      '.....KAK.KAK....',
      '.....KAK.KAK....',
      '....KABK.KBAK...',
      '..KABBBBBBBBBAK.',
      '.KABB.EE.EE.BAK.',
      '.KABBBBBBBBBBBAK',
      '.KABB.NNNN.BBAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBAK..',
      '...KBBBBBBBBK...',
      '...KBBBBBBBBK...',
      '....KBBBBBBK....',
      '................',
      '................',
      '................',
    ],
  },
  childhood: {
    eyeColor: 'outline',
    map: [
      '....KAK..KAK....',
      '....KAK..KAK....',
      '....KAK..KAK....',
      '...KABK..KBAK...',
      '..KABBBBBBBBBAK.',
      '.KABBBBBBBBBBBAK',
      '.KABB.EE.EE.BAK.',
      '.KABB.NNNN.BBAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBAK..',
      '..KBBBBBBBBBBK..',
      '..KBBBBBBBBBBK..',
      '..KBB......BBK..',
      '...KK......KK...',
      '................',
      '................',
    ],
  },
  growth: {
    eyeColor: 'outline',
    map: [
      '....KAK..KAK....',
      '....KAK..KAK....',
      '...KABK..KBAK...',
      '..KABBBBBBBBBAK.',
      '.KABBBBBBBBBBBAK',
      '.KABB.EE.EE.BAK.',
      '.KABB.NNNN.BBAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBAK..',
      '.KBBBBBBBBBBBBK.',
      'KBBBBBBBBBBBBBBK',
      'KBBBBBBBBBBBBBBK',
      '.KBB........BBK.',
      '.KBB.K....K.BBK.',
      '..KK.K....K.KK..',
      '................',
    ],
  },
  maturity: {
    eyeColor: 'outline',
    map: [
      '...KAK....KAK...',
      '...KAK....KAK...',
      '..KABK....KBAK..',
      '.KABBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KAB.EE....EE.BAK',
      'KABBBBBBBBBBBBAK',
      'KAB.NNNNNN.BBAK.',
      'KABBBBBBBBBBBBAK',
      'KBBBBBBBBBBBBBBK',
      'KBBBBBBBBBBBBBBK',
      'KBB..KBBBBK..BBK',
      'KBB..KBBBBK..BBK',
      '.KK..KBBBBK..KK.',
      '................',
      '................',
    ],
  },
};

// ─── 여우 (fox) - 뾰족한 귀, 주황색 몸, 특색 있는 주둥이 ───
const FOX: AnimalPixelData = {
  baby: {
    eyeColor: 'outline',
    map: [
      '.....KAK.KAK....',
      '....KABBBBBBAK..',
      '...KABBBBBBBBAK.',
      '..KABBBBBBBBBAK.',
      '..KABB.EE.EE.AK.',
      '..KABBBBBBBBBAK.',
      '..KAABBNNNNBBAK.',
      '..KABBBBBBBBBAK.',
      '...KABBBBBBBBAK.',
      '....KBBBBBBBBK..',
      '....KBBBBBBBBK..',
      '.....KBBBBBBK...',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  childhood: {
    eyeColor: 'outline',
    map: [
      '...KAK....KAK...',
      '..KAAK....KAAK..',
      '..KABBBBBBBBBAK.',
      '.KABBBBBBBBBBBAK',
      '.KABB.EE..EE.BAK',
      '.KABBBBBBBBBBBAK',
      '.KAAB.NNNN.BAAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBAK..',
      '..KBBBBBBBBBBK..',
      '..KBBBBBBBBBBK..',
      '..KBB......BBK..',
      '..KBB......BBK..',
      '...KK......KK...',
      '................',
      '................',
    ],
  },
  growth: {
    eyeColor: 'outline',
    map: [
      '..KAK.....KAK...',
      '..KAAK....KAAK..',
      '.KABBBBBBBBBBBAK',
      'KABBBBBBBBBBBAK.',
      'KAB..EE..EE..BAK',
      'KAABBBBBBBBBBAAK',
      'KAAB.NNNN.BBAAK.',
      'KABBBBBBBBBBBAK.',
      '.KABBBBBBBBBBBAK',
      '.KBBBBBBBBBBBBK.',
      'KBBBBBBBBBBBBBBK',
      'KBBBBBBBBBBBBBBK',
      '.KBB........BBK.',
      '.KBB.K....K.BBK.',
      '..KK.K....K.KK..',
      '................',
    ],
  },
  maturity: {
    eyeColor: 'outline',
    map: [
      '..KAK......KAK..',
      '.KAAK......KAAK.',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KAB.EE....EE.BAK',
      'KAABBBBBBBBBAAK.',
      'KAAB.NNNNNN.BAK.',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KBBBBBBBBBBBBBBK',
      'KBBBBBBBBBBBBBBK',
      'KBB..KBBBBK..BBK',
      'KBB..KBBBBK..BBK',
      '.KK..KBBBBK..KK.',
      '................',
      '................',
    ],
  },
};

// ─── 판다 (panda) - 흰 몸+검은 눈 패치/귀, 둥근 체형 ───
// B=흰색몸통, A=검은패치/귀
const PANDA: AnimalPixelData = {
  baby: {
    eyeColor: 'outline',
    map: [
      '....KAAK.KAAK...',
      '...KABBBBBBBBAK.',
      '..KABBBBBBBBBAK.',
      '.KABBB.AEA.AEBAK',
      '.KABBBAAAAAAA.AK',
      '.KABB.NNNN.BBAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBAK..',
      '...KABBBBBBBAK..',
      '....KBBBBBBBBK..',
      '....KBBBBBBBBK..',
      '.....KBBBBBBK...',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  childhood: {
    eyeColor: 'outline',
    map: [
      '...KAAK..KAAK...',
      '..KABBBBBBBBBAK.',
      '.KABBBBBBBBBBBAK',
      '.KABBB.AEAAE.BAK',
      '.KABBBAAAAAAABAK',
      '.KABB.NNNN.BBAK.',
      '.KABBBBBBBBBBBAK',
      '..KABBBBBBBBAK..',
      '..KBBBBBBBBBBK..',
      '..KBBBBBBBBBBK..',
      '..KABBB..BBBAK..',
      '..KABBB..BBBAK..',
      '...KABB..BBAK...',
      '....KK....KK....',
      '................',
      '................',
    ],
  },
  growth: {
    eyeColor: 'outline',
    map: [
      '..KAAK....KAAK..',
      '.KABBBBBBBBBBBAK',
      'KABBBBBBBBBBBAK.',
      'KABB..AEAAE..BAK',
      'KABBBAAAAAAABAK.',
      'KAB..NNNNNN..AK.',
      'KABBBBBBBBBBBAK.',
      '.KABBBBBBBBBBBAK',
      '.KBBBBBBBBBBBBK.',
      '.KABBBBBBBBBBAK.',
      'KBBBBBBBBBBBBBBK',
      'KBBBBBBBBBBBBBBK',
      '.KAB......BAK...',
      '.KAB......BAK...',
      '..KK......KK....',
      '................',
    ],
  },
  maturity: {
    eyeColor: 'outline',
    map: [
      '.KAAK......KAAK.',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KAB.AEAAAE..BAK.',
      'KABBAAAAAAAABAK.',
      'KAB.NNNNNN..AK..',
      'KABBBBBBBBBBBBAK',
      'KABBBBBBBBBBBBAK',
      'KBBBBBBBBBBBBBBK',
      'KABBBBBBBBBBBBAK',
      'KBBBBBBBBBBBBBBK',
      'KABBKBBBBKBBKBBK',
      'KABBKBBBBKBBKBBK',
      '.KAK.KBBK.KAK...',
      '................',
      '................',
    ],
  },
};

export const PIX = { dog: DOG, cat: CAT, rabbit: RABBIT, fox: FOX, panda: PANDA };
